version: "3.0"
services:

  api:
    ports:
    - "5001:5001"
    volumes:
      - "./api/src:/app/src"
    command: ["run","start-watch"]

  web:
    environment:
      - PORT=5000
    command: ["start"]
    ports:
      - "5000:5000"
    volumes:
      - "./web/src:/app/src"

  selenium:
    image: selenium/standalone-chrome-debug
    ports:
      - "4444:4444"
      - "5900:5900"

  tests:
    volumes:
      - "./tests/features:/app/features"
