version: "3.0"
services:

  web:
    build: "web"

  selenium:
    image: yukinying/chrome-headless-browser-selenium
    cap_add:
      - SYS_ADMIN
    shm_size: 1024m
    depends_on:
      - "web"

  tests:
    build: "tests"
    depends_on:
      - "selenium"