version: "3.0"
services:

  web:
    build: "web"

  selenium:
    image: selenium/standalone-chrome-debug
    depends_on:
      - "web"

  tests:
    build: "tests"
    depends_on:
      - "selenium"