version: "3.0"
services:

  api:
    build: "api"

  web:
    build: "web"
    depends_on:
      - "api"

  selenium:
    image: selenium/standalone-chrome
    depends_on:
      - "web"

  tests:
    build: "tests"
    depends_on:
      - "selenium"